import { TableHeaderDataInterface } from "../../../Interface/TableInterface/TableInterface";

export const PatientHeaderTableData: TableHeaderDataInterface[] = [
  { id: "Name", label: "Patient Name" },
  { id: "DateOfBirth", label: "Date Of Birth" },
  { id: "Nationality", label: "Nationality" },
  { id: "PhoneNumber", label: "Phone Number" },
  { id: "EmailAddress", label: "Email Address" },

  { id: "DueAmount", label: "Due Amount" },
];

export const PatientResponsiveHeaderTableData: TableHeaderDataInterface[] = [
  { id: "Name", label: "Patient Name" },
  { id: "DateOfBirth", label: "table.Date Of Birth" },
  { id: "DueAmount", label: "table.Due Amount" },
];

export const PatientTableData = [
  {
    SourceId: "edfgrtygfr",
    Name: "Sara Khalid",
    FileId: "F1001",
    DateOfBirth: new Date(1990, 5, 15),
    Nationality: "USA",
    PhoneNumber: "+1 123-456-7890",
    EmailAddress: "sara@example.com",

    DueAmount: "150.75",
  },
  {
    SourceId: "wqdewqedwqd",
    Name: "Samah Ahmed",
    FileId: "F1002",
    DateOfBirth: new Date(1985, 10, 22),
    Nationality: "Canada",
    PhoneNumber: "+1 987-654-3210",
    EmailAddress: "samah@example.com",

    DueAmount: "200.0",
  },
  {
    SourceId: "qwdfegt55r4e3w",
    Name: "Amina Hassan",
    FileId: "F1003",
    DateOfBirth: new Date(1992, 3, 9),
    Nationality: "Pakistan",
    PhoneNumber: "+92 300-1234567",
    EmailAddress: "amina@example.com",

    DueAmount: "75.5",
  },
  {
    SourceId: "wqrfewqa",
    Name: "Afaf Mohammed",
    FileId: "F1004",
    DateOfBirth: new Date(1988, 7, 30),
    Nationality: "Mexico",
    PhoneNumber: "+52 55-9876-5432",
    EmailAddress: "afaf@example.com",

    DueAmount: "300.0",
  },
  {
    SourceId: "ert3e3w2wsdef",
    Name: "Layla Hussein",
    FileId: "F1005",
    DateOfBirth: new Date(1995, 1, 5),
    Nationality: "Ireland",
    PhoneNumber: "+353 85-678-9102",
    EmailAddress: "layla@example.com",

    DueAmount: "50.0",
  },
  {
    SourceId: "edfgrtygwqwwwfr",
    Name: "Mariam Omar",
    FileId: "F1006",
    DateOfBirth: new Date(1982, 11, 12),
    Nationality: "China",
    PhoneNumber: "+86 139-4567-8901",
    EmailAddress: "mariam@example.com",

    DueAmount: "500.0",
  },
  {
    SourceId: "edfgwqewqrt4rtygfr",
    Name: "Fatima Al-Farsi",
    FileId: "F1007",
    DateOfBirth: new Date(1990, 4, 18),
    Nationality: "UAE",
    PhoneNumber: "+971 50-987-6543",
    EmailAddress: "fatima@example.com",

    DueAmount: "275.25",
  },
  {
    SourceId: "edfgrtygferwedasdsdr",
    Name: "Hana Saeed",
    FileId: "F1008",
    DateOfBirth: new Date(1987, 6, 8),
    Nationality: "Brazil",
    PhoneNumber: "+55 21-3456-7890",
    EmailAddress: "hana@example.com",

    DueAmount: "125.0",
  },
  {
    SourceId: "ewrdewerfwe",
    Name: "Noor Abdullah",
    FileId: "F1009",
    DateOfBirth: new Date(1993, 9, 14),
    Nationality: "Germany",
    PhoneNumber: "+49 170-123-4567",
    EmailAddress: "noor@example.com",

    DueAmount: "180.0",
  },
  {
    SourceId: "asdfghy6trew",
    Name: "Rania Khalil",
    FileId: "F1010",
    DateOfBirth: new Date(1989, 2, 27),
    Nationality: "Egypt",
    PhoneNumber: "+20 100-234-5678",
    EmailAddress: "rania@example.com",

    DueAmount: "220.0",
  },
  {
    SourceId: "wsefgbhytgfrde",
    Name: "Zainab Kareem",
    FileId: "F1011",
    DateOfBirth: new Date(1991, 8, 19),
    Nationality: "Italy",
    PhoneNumber: "+39 320-456-7890",
    EmailAddress: "zainab@example.com",
    Cycles: "3",
    DueAmount: "190.5",
  },
  {
    SourceId: "asdcfvbjh6ygt",
    Name: "Salma Youssef",
    FileId: "F1012",
    DateOfBirth: new Date(1986, 0, 10),
    Nationality: "UK",
    PhoneNumber: "+44 7911-123456",
    EmailAddress: "salma@example.com",
    Cycles: "6",
    DueAmount: "350.0",
  },
  {
    SourceId: "frgethy6tr",
    Name: "Aya Nasser",
    FileId: "F1013",
    DateOfBirth: new Date(1994, 5, 21),
    Nationality: "Japan",
    PhoneNumber: "+81 90-9876-5432",
    EmailAddress: "aya@example.com",
    Cycles: "2",
    DueAmount: "160.75",
  },
  {
    SourceId: "safgrfedws",
    Name: "Elham Jaber",
    FileId: "F1014",
    DateOfBirth: new Date(1983, 11, 5),
    Nationality: "Russia",
    PhoneNumber: "+7 921-234-5678",
    EmailAddress: "elham@example.com",
    Cycles: "4",
    DueAmount: "295.0",
  },
  {
    SourceId: "dscvbhgf",
    Name: "Nadia Rahman",
    FileId: "F1015",
    DateOfBirth: new Date(1980, 7, 25),
    Nationality: "Senegal",
    PhoneNumber: "+221 77-123-4567",
    EmailAddress: "nadia@example.com",
    Cycles: "5",
    DueAmount: "210.0",
  },
];
