import { TableHeaderDataInterface } from "../../../../Interface/TableInterface/TableInterface";

export const TreatmentHistoryColumnData: TableHeaderDataInterface[] = [
  { id: "Treatment", label: "Treatment" },
  { id: "Progress", label: "Progress" },
  { id: "Date", label: "Date" },
  { id: "Details", label: "Details" },
];

export const TreatmentHistoryData = [
  {
    SourceId: "dfret4y654tred",
    Treatment: "Ovarian Stimulation",
    Progress: "Ongoing (Ovarian Stimulation)",
    Date: new Date(2025, 1, 5, 9, 30),
    Details: "Scheduled",
  },
  {
    SourceId: "abc123xyz456",
    Treatment: "Egg Retrieval",
    Progress: "Completed",
    Date: new Date(2025, 1, 10, 14, 0),
    Details: "Successful retrieval of 12 eggs",
  },
  {
    SourceId: "lkj098mnb765",
    Treatment: "Medication Therapy",
    Progress: "Canceled",
    Date: new Date(2025, 1, 15, 10, 15),
    Details: "Treatment halted due to adverse reaction",
  },
  {
    SourceId: "plm345qwe678",
    Treatment: "Embryo Transfer",
    Progress: "Rescheduled",
    Date: new Date(2025, 1, 20, 11, 45),
    Details: "Delayed due to doctor availability",
  },
  {
    SourceId: "xyz789abc123",
    Treatment: "Hormonal Therapy",
    Progress: "Ongoing (Ovarian Stimulation)",
    Date: new Date(2025, 1, 25, 9, 0),
    Details: "Patient responding well to treatment",
  },
  {
    SourceId: "tre456yhn789",
    Treatment: "Embryo Transfer",
    Progress: "Completed",
    Date: new Date(2025, 2, 1, 13, 30),
    Details: "Transfer of two high-quality embryos",
  },
  {
    SourceId: "hgf234vbn567",
    Treatment: "Follow-up Scan",
    Progress: "Canceled",
    Date: new Date(2025, 2, 5, 8, 30),
    Details: "Patient unable to attend",
  },
  {
    SourceId: "zxc098asd765",
    Treatment: "Pregnancy Test",
    Progress: "Rescheduled",
    Date: new Date(2025, 2, 10, 10, 0),
    Details: "Rescheduled due to unexpected cycle changes",
  },
  {
    SourceId: "bnm321lkj654",
    Treatment: "Ovarian Stimulation",
    Progress: "Ongoing (Ovarian Stimulation)",
    Date: new Date(2025, 2, 15, 9, 15),
    Details: "New cycle started",
  },
  {
    SourceId: "poi876wer543",
    Treatment: "Egg Retrieval",
    Progress: "Completed",
    Date: new Date(2025, 2, 20, 14, 30),
    Details: "10 eggs retrieved, 7 fertilized successfully",
  },
  {
    SourceId: "mnb654vcx098",
    Treatment: "Embryo Transfer",
    Progress: "Canceled",
    Date: new Date(2025, 2, 25, 12, 0),
    Details: "Medical concerns, postponed indefinitely",
  },
  {
    SourceId: "asd987qwe654",
    Treatment: "Hormonal Therapy",
    Progress: "Ongoing (Ovarian Stimulation)",
    Date: new Date(2025, 3, 1, 9, 45),
    Details: "Stable response to medication",
  },
  {
    SourceId: "lkj543zxc321",
    Treatment: "Embryo Transfer",
    Progress: "Completed",
    Date: new Date(2025, 3, 5, 13, 0),
    Details: "Successful implantation",
  },
  {
    SourceId: "yhn678tre456",
    Treatment: "Pregnancy Test",
    Progress: "Canceled",
    Date: new Date(2025, 3, 10, 10, 30),
    Details: "Patient missed appointment",
  },
  {
    SourceId: "vbn234mnb987",
    Treatment: "Follow-up Consultation",
    Progress: "Rescheduled",
    Date: new Date(2025, 3, 15, 11, 0),
    Details: "Doctor's request",
  },
  {
    SourceId: "zxc567qwe876",
    Treatment: "Ovarian Stimulation",
    Progress: "Ongoing (Ovarian Stimulation)",
    Date: new Date(2025, 3, 20, 9, 0),
    Details: "New treatment cycle started",
  },
  {
    SourceId: "qaz123wsx456",
    Treatment: "Egg Retrieval",
    Progress: "Completed",
    Date: new Date(2025, 3, 25, 14, 15),
    Details: "9 eggs retrieved, 6 fertilized",
  },
  {
    SourceId: "edc789rfv234",
    Treatment: "Embryo Transfer",
    Progress: "Canceled",
    Date: new Date(2025, 4, 1, 12, 45),
    Details: "Patient opted for alternative treatment",
  },
  {
    SourceId: "tgb987yhn654",
    Treatment: "Pregnancy Test",
    Progress: "Rescheduled",
    Date: new Date(2025, 4, 5, 10, 15),
    Details: "Rescheduled due to lab unavailability",
  },
  {
    SourceId: "ujm654ikm987",
    Treatment: "Follow-up Scan",
    Progress: "Scheduled",
    Date: new Date(2025, 4, 10, 11, 30),
    Details: "Routine check-up",
  },
];
