import { TableHeaderDataInterface } from "../../../../Interface/TableInterface/TableInterface";

export const AppointmentHistoryColumnData: TableHeaderDataInterface[] = [
  { id: "Event", label: "Event" },
  { id: "Date", label: "Date" },
  { id: "Time", label: "Time" },
  { id: "Status", label: "Status" },
  { id: "Notes", label: "Notes" },
];

export const AppointmentHistoryData = [
  {
    SourceId: "dfret4y654tred",
    Event: "Project Kickoff",
    DateAndTime: new Date(2025, 1, 5, 9, 30),
    Status: "Done",
    Notes: "Initial meeting to discuss project scope.",
  },
  {
    SourceId: "sdfgfrefsd",
    Event: "Team Lunch",
    DateAndTime: new Date(2025, 2, 12, 12, 0),
    Status: "Upcoming",
    Notes: "Celebrating the successful product launch.",
  },
  {
    SourceId: "defrgtygferwrfesd",
    Event: "Client Presentation",
    DateAndTime: new Date(2025, 3, 20, 15, 45),
    Status: "Canceled",
    Notes: "Prepare slides and reports for the client.",
  },
  {
    SourceId: "trgeg45fd",
    Event: "System Upgrade",
    DateAndTime: new Date(2025, 4, 8, 23, 0),
    Status: "Upcoming",
    Notes: "Upgrade backend services to the latest version.",
  },
  {
    SourceId: "ertgerfcsdcas",
    Event: "Marketing Campaign Launch",
    DateAndTime: new Date(2025, 5, 15, 10, 15),
    Status: "Canceled",
    Notes: "Social media ads and email campaigns go live.",
  },
  {
    SourceId: "ewfcwsdc",
    Event: "Annual Performance Review",
    DateAndTime: new Date(2025, 6, 3, 14, 0),
    Status: "Done",
    Notes: "Review employee performance and set goals.",
  },
  {
    SourceId: "ewgftbvfdcs",
    Event: "Bug Fix Sprint",
    DateAndTime: new Date(2025, 7, 21, 8, 30),
    Status: "Upcoming",
    Notes: "Address critical bugs reported by users.",
  },
  {
    SourceId: "wegrbtf4rdeswa",
    Event: "Quarterly Financial Meeting",
    DateAndTime: new Date(2025, 8, 10, 16, 0),
    Status: "Canceled",
    Notes: "Review revenue and expense reports.",
  },
  {
    SourceId: "wefwxas",
    Event: "Product Demo",
    DateAndTime: new Date(2025, 9, 27, 11, 30),
    Status: "Done",
    Notes: "Showcased new features to stakeholders.",
  },
  {
    SourceId: "erfcdxaxas",
    Event: "Security Audit",
    DateAndTime: new Date(2025, 10, 5, 13, 15),
    Status: "Done",
    Notes: "Assess vulnerabilities and compliance issues.",
  },
  {
    SourceId: "dsfvbnhtyrg",
    Event: "Conference Call",
    DateAndTime: new Date(2025, 11, 18, 17, 0),
    Status: "Done",
    Notes: "Weekly update with international teams.",
  },
  {
    SourceId: "ewfwaxwefrefd",
    Event: "Training Workshop",
    DateAndTime: new Date(2025, 0, 22, 9, 45),
    Status: "Upcoming",
    Notes: "Skill development session for employees.",
  },
  {
    SourceId: "asferfcdsa",
    Event: "Hackathon",
    DateAndTime: new Date(2025, 1, 14, 20, 0),
    Status: "Done",
    Notes: "48-hour coding event with prizes.",
  },
  {
    SourceId: "sdfgrtedwscds",
    Event: "Product Testing",
    DateAndTime: new Date(2025, 2, 25, 18, 30),
    Status: "Done",
    Notes: "QA team will perform extensive tests.",
  },
  {
    SourceId: "sdf4rfcdscsd",
    Event: "New Hire Orientation",
    DateAndTime: new Date(2025, 3, 7, 10, 0),
    Status: "Done",
    Notes: "Introduction session for new employees.",
  },
  {
    SourceId: "dfret4y654tred",
    Event: "Office Relocation",
    DateAndTime: new Date(2025, 4, 30, 7, 45),
    Status: "Upcoming",
    Notes: "Moving to a new office building downtown.",
  },
  {
    SourceId: "dsaderfd",
    Event: "Board Meeting",
    DateAndTime: new Date(2025, 5, 19, 15, 30),
    Status: "Done",
    Notes: "Discussion on company strategy and vision.",
  },
  {
    SourceId: "wehytgrfdc",
    Event: "Server Maintenance",
    DateAndTime: new Date(2025, 6, 9, 2, 0),
    Status: "Canceled",
    Notes: "Planned downtime for database migration.",
  },
  {
    SourceId: "wqdgtrefd",
    Event: "Charity Fundraiser",
    DateAndTime: new Date(2025, 7, 16, 19, 0),
    Status: "Done",
    Notes: "Raising funds for community development.",
  },
  {
    SourceId: "htyrgerrt",
    Event: "Product Release Party",
    DateAndTime: new Date(2025, 8, 24, 21, 0),
    Status: "Done",
    Notes: "Celebration of the successful product launch.",
  },
];
