import { TableHeaderDataInterface } from "../../Interface/TableInterface/TableInterface";
import { formatPhoneNumberLTR, toArabicDigits } from "../../utils/translates";

export const HeaderColumns: TableHeaderDataInterface[] = [
  { id: "Name", label: "table.Name" },
  { id: "ID", label: "table.ID" },
  { id: "ContactDetails", label: "table.Contact Details" },
  { id: "CurrentStatus", label: "table.Current Status" },
  { id: "Status", label: "table.Status" },
];

export const DummyData = [
  {
    Name: "Hadi Shouman",
    ID: "Hadi_Shoumandfssfsa",
    ContactDetails: [
      formatPhoneNumberLTR("+961 76837264"),
      "Hadi@ektolife.com",
    ],
    CurrentStatus: "table.Under treatment",
    Status: "table.Paid",
  },
  {
    Name: "Sultana Nasser",
    ID: "Sultana@dsfgbtrfedxs",
    ContactDetails: [
      formatPhoneNumberLTR("+971 987-6543"),
      "Hadi@ektolife.com",
    ],
    CurrentStatus: "table.Under treatment",
    Status: "table.Unpaid",
  },
  {
    Name: "Amir Haddad",
    ID: "Amir_Haddad12345",
    ContactDetails: ["+971 12345678", "Amir@ektolife.com"],
    CurrentStatus: "table.Under treatment",
    Status: "table.Paid",
  },
  {
    Name: "Layla Karim",
    ID: "Layla_KarimABC",
    ContactDetails: ["+971 98765432", "Layla@ektolife.com"],
    CurrentStatus: "table.Recovered",
    Status: "table.Paid",
  },
  {
    Name: "Zainab Hakim",
    ID: "Zainab_HakimXYZ",
    ContactDetails: ["+971 56473829", "Zainab@ektolife.com"],
    CurrentStatus: "table.Under observation",
    Status: "table.Unpaid",
  },
  {
    Name: "Omar Khaled",
    ID: "Omar_Khaled2024",
    ContactDetails: ["+971 87654321", "Omar@ektolife.com"],
    CurrentStatus: "table.Discharged",
    Status: "table.Paid",
  },
  {
    Name: "Fatima Noor",
    ID: "Fatima_Noor888",
    ContactDetails: ["+971 11223344", "Fatima@ektolife.com"],
    CurrentStatus: "table.Under treatment",
    Status: "table.Unpaid",
  },
  {
    Name: "Yusuf Ameen",
    ID: "Yusuf_Ameen567",
    ContactDetails: ["+971 44556677", "Yusuf@ektolife.com"],
    CurrentStatus: "table.Recovered",
    Status: "table.Paid",
  },
  {
    Name: "Nour Salem",
    ID: "Nour_Salem4321",
    ContactDetails: ["+971 22334455", "Nour@ektolife.com"],
    CurrentStatus: "table.Under observation",
    Status: "table.Unpaid",
  },
  {
    Name: "Khaled Omar",
    ID: "Khaled_Omar7654",
    ContactDetails: ["+971 66778899", "Khaled@ektolife.com"],
    CurrentStatus: "table.Under treatment",
    Status: "table.Paid",
  },
  {
    Name: "Reem Fathi",
    ID: "Reem_Fathi9012",
    ContactDetails: ["+971 99887766", "Reem@ektolife.com"],
    CurrentStatus: "table.Discharged",
    Status: "table.Unpaid",
  },
  {
    Name: "Ahmed Sami",
    ID: "Ahmed_Sami1234",
    ContactDetails: ["+971 33445566", "Ahmed@ektolife.com"],
    CurrentStatus: "table.Under observation",
    Status: "table.Paid",
  },
  {
    Name: "Lina Mounir",
    ID: "Lina_Mounir9876",
    ContactDetails: ["+971 22334455", "Lina@ektolife.com"],
    CurrentStatus: "table.Under treatment",
    Status: "table.Unpaid",
  },
  {
    Name: "Hassan Ibrahim",
    ID: "Hassan_Ibrahim5432",
    ContactDetails: ["+971 77889900", "Hassan@ektolife.com"],
    CurrentStatus: "table.Recovered",
    Status: "table.Paid",
  },
  {
    Name: "Maya Zaid",
    ID: "Maya_Zaid76543",
    ContactDetails: ["+971 55443322", "Maya@ektolife.com"],
    CurrentStatus: "table.Discharged",
    Status: "table.Paid",
  },
  {
    Name: "Ali Jaber",
    ID: "Ali_Jaber1098",
    ContactDetails: ["+971 88776655", "Ali@ektolife.com"],
    CurrentStatus: "table.Under observation",
    Status: "table.Unpaid",
  },
  {
    Name: "Sara Khalil",
    ID: "Sara_Khalil3210",
    ContactDetails: ["+971 77665544", "Sara@ektolife.com"],
    CurrentStatus: "table.Under treatment",
    Status: "table.Paid",
  },
  {
    Name: "Rami Hasan",
    ID: "Rami_Hasan6789",
    ContactDetails: ["+971 44556677", "Rami@ektolife.com"],
    CurrentStatus: "table.Under observation",
    Status: "table.Unpaid",
  },
  {
    Name: "Mariam Adel",
    ID: "Mariam_Adel4567",
    ContactDetails: ["+971 99887766", "Mariam@ektolife.com"],
    CurrentStatus: "table.Recovered",
    Status: "table.Paid",
  },
  {
    Name: "Fadi Hatem",
    ID: "Fadi_Hatem3456",
    ContactDetails: ["+971 33445566", "Fadi@ektolife.com"],
    CurrentStatus: "table.Discharged",
    Status: "table.Unpaid",
  },
  {
    Name: "Jana Tariq",
    ID: "Jana_Tariq8765",
    ContactDetails: ["+971 66778899", "Jana@ektolife.com"],
    CurrentStatus: "table.Under observation",
    Status: "table.Paid",
  },
  {
    Name: "Samir Rahim",
    ID: "Samir_Rahim5432",
    ContactDetails: ["+971 44556677", "Samir@ektolife.com"],
    CurrentStatus: "table.Under treatment",
    Status: "table.Unpaid",
  },
];
