import { Prf1 } from "../../constants/Pics/Pics";
import { CalendarEvent } from "./CalenderInterface";

const now = new Date();
const CURRENT_YEAR = now.getFullYear();
const CURRENT_MONTH = now.getMonth(); // 0-based index

const dateAt = (day: number, hour: number, minute: number = 0) =>
  new Date(CURRENT_YEAR, CURRENT_MONTH, day, hour, minute);

export const myEventsList: CalendarEvent[] = [
  {
    title: "Survey 1",
    start: dateAt(2, 9),
    end: dateAt(2, 10),
    type: "survey",
    patientId: "P001",
    patientName: "Alice Johnson",
    patientProfile: Prf1,
    patient_phoneNumber: "555-125-4567",
    patient_email: "alice.johnson@example.com",
    doctorId: "D001",
    doctorName: "Dr. Emily Carter",
    reason: "Annual Checkup",
    Note: "Patient mentioned mild headaches.",
    done: true,
  },
  {
    title: "Survey 2",
    start: dateAt(3, 11),
    end: dateAt(3, 12),
    type: "survey",
    patientId: "P002",
    patientName: "Bob Smith",
    patientProfile: Prf1,
    patient_phoneNumber: "555-987-6545",
    patient_email: "bob.smith@example.com",
    doctorId: "D002",
    doctorName: "Dr. Olivia Chen",
    reason: "Follow-up Visit",
    Note: "Review of lab results.",
    done: false,
  },
  {
    title: "Survey 3",
    start: dateAt(4, 10),
    end: dateAt(4, 11),
    type: "survey",
    patientId: "P003",
    patientName: "Carla Mendes",
    patientProfile: Prf1,
    patient_phoneNumber: "555-333-7890",
    patient_email: "carla.mendes@example.com",
    doctorId: "D003",
    doctorName: "Dr. James Lee",
    reason: "Skin Rash",
    Note: "Prescribed ointment.",
    done: true,
  },
  {
    title: "Survey 4",
    start: dateAt(5, 9),
    end: dateAt(5, 10),
    type: "survey",
    patientId: "P004",
    patientName: "David Kim",
    patientProfile: Prf1,
    patient_phoneNumber: "555-444-8888",
    patient_email: "david.kim@example.com",
    doctorId: "D004",
    doctorName: "Dr. Noah Reed",
    reason: "Cold Symptoms",
    Note: "Advised rest and fluids.",
    done: false,
  },
  {
    title: "Survey 5",
    start: dateAt(6, 14),
    end: dateAt(6, 15),
    type: "survey",
    patientId: "P005",
    patientName: "Eva Long",
    patientProfile: Prf1,
    patient_phoneNumber: "555-666-1234",
    patient_email: "eva.long@example.com",
    doctorId: "D001",
    doctorName: "Dr. Emily Carter",
    reason: "Post-Surgery Checkup",
    Note: "Healing well.",
    done: true,
  },
  {
    title: "Survey 6",
    start: dateAt(7, 8),
    end: dateAt(7, 9),
    type: "survey",
    patientId: "P006",
    patientName: "Frank Nash",
    patientProfile: Prf1,
    patient_phoneNumber: "555-222-5678",
    patient_email: "frank.nash@example.com",
    doctorId: "D002",
    doctorName: "Dr. Olivia Chen",
    reason: "Back Pain",
    Note: "Prescribed physiotherapy.",
    done: false,
  },
  {
    title: "Survey 7",
    start: dateAt(8, 10),
    end: dateAt(8, 11),
    type: "survey",
    patientId: "P007",
    patientName: "Grace Lee",
    patientProfile: Prf1,
    patient_phoneNumber: "555-789-9999",
    patient_email: "grace.lee@example.com",
    doctorId: "D003",
    doctorName: "Dr. James Lee",
    reason: "Allergy Testing",
    Note: "Mild seasonal allergy confirmed.",
    done: true,
  },
  {
    title: "Survey 8",
    start: dateAt(9, 13),
    end: dateAt(9, 14),
    type: "survey",
    patientId: "P008",
    patientName: "Harry Ford",
    patientProfile: Prf1,
    patient_phoneNumber: "555-888-0000",
    patient_email: "harry.ford@example.com",
    doctorId: "D004",
    doctorName: "Dr. Noah Reed",
    reason: "Annual Blood Test",
    Note: "Results pending.",
    done: false,
  },
  {
    title: "Survey 9",
    start: dateAt(10, 9),
    end: dateAt(10, 10),
    type: "survey",
    patientId: "P009",
    patientName: "Isla Ray",
    patientProfile: Prf1,
    patient_phoneNumber: "555-111-2222",
    patient_email: "isla.ray@example.com",
    doctorId: "D001",
    doctorName: "Dr. Emily Carter",
    reason: "Thyroid Follow-up",
    Note: "No changes in condition.",
    done: true,
  },
  {
    title: "Survey 10",
    start: dateAt(11, 11),
    end: dateAt(11, 12),
    type: "survey",
    patientId: "P010",
    patientName: "Jake Olson",
    patientProfile: Prf1,
    patient_phoneNumber: "555-000-5555",
    patient_email: "jake.olson@example.com",
    doctorId: "D002",
    doctorName: "Dr. Olivia Chen",
    reason: "Nutrition Advice",
    Note: "Suggested Mediterranean diet.",
    done: true,
  },
  {
    title: "Survey 11",
    start: dateAt(12, 8),
    end: dateAt(12, 9),
    type: "survey",
    patientId: "P011",
    patientName: "Kate Hudson",
    patientProfile: Prf1,
    patient_phoneNumber: "555-321-4321",
    patient_email: "kate.hudson@example.com",
    doctorId: "D003",
    doctorName: "Dr. James Lee",
    reason: "Blood Pressure Check",
    Note: "Stabilized levels.",
    done: false,
  },
  {
    title: "Survey 12",
    start: dateAt(13, 12),
    end: dateAt(13, 13),
    type: "survey",
    patientId: "P012",
    patientName: "Liam Scott",
    patientProfile: Prf1,
    patient_phoneNumber: "555-654-7654",
    patient_email: "liam.scott@example.com",
    doctorId: "D004",
    doctorName: "Dr. Noah Reed",
    reason: "Headache Evaluation",
    Note: "CT scan recommended.",
    done: false,
  },
  {
    title: "Survey 13",
    start: dateAt(14, 15),
    end: dateAt(14, 16),
    type: "survey",
    patientId: "P013",
    patientName: "Mona Patel",
    patientProfile: Prf1,
    patient_phoneNumber: "555-999-1212",
    patient_email: "mona.patel@example.com",
    doctorId: "D001",
    doctorName: "Dr. Emily Carter",
    reason: "Routine Physical",
    Note: "No complaints reported.",
    done: true,
  },
  {
    title: "Survey 14",
    start: dateAt(15, 9),
    end: dateAt(15, 10),
    type: "survey",
    patientId: "P014",
    patientName: "Nathan Cole",
    patientProfile: Prf1,
    patient_phoneNumber: "555-000-7878",
    patient_email: "nathan.cole@example.com",
    doctorId: "D002",
    doctorName: "Dr. Olivia Chen",
    reason: "Post-Vaccine Follow-up",
    Note: "Minor arm soreness noted.",
    done: true,
  },
];





// import { HadiProfile, MadonaImg, Prf1 } from "../../constants/Pics/Pics";
// import { CalendarEvent } from "./CalenderInterface";

// export const myEventsList: CalendarEvent[] = [
//   {
//     title: "Survey 1",
//     start: new Date(2025, 5, 2, 1, 0),
//     end: new Date(2025, 5, 2, 2, 0),
//     type: "survey",
//     patientId: "P001",
//     patientName: "Alice Johnson",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-125-4567",
//     patient_email: "alice.johnson@example.com",
//     doctorId: "D001",
//     doctorName: "Dr. Emily Carter",
//     reason: "Annual Checkup",
//     Note: "Patient mentioned mild headaches.",
//     done: true,
//   },
//   {
//     title: "Survey 2",
//     start: new Date(2025, 5, 5, 2, 0),
//     end: new Date(2025, 5, 5, 5, 0),
//     type: "survey",
//     patientId: "P002",
//     patientName: "Bob Smith",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-987-6545",
//     patient_email: "bob.smith@example.com",
//     doctorId: "D002",
//     doctorName: "Dr. Olivia Chen",
//     reason: "Follow-up Visit",
//     Note: "Review of lab results.",
//     done: false,
//   },
//   {
//     title: "Survey 5",
//     start: new Date(2025, 5, 17, 10, 0),
//     end: new Date(2025, 5, 17, 11, 0),
//     type: "survey",
//     patientId: "P005",
//     patientName: "Charlie Lee",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-521-7890",
//     patient_email: "charlie.lee@example.com",
//     doctorId: "D001",
//     doctorName: "Dr. Emily Carter",
//     reason: "Post-Surgery Consultation",
//     Note: "Patient is healing well.",
//     done: true,
//   },
//   {
//     title: "Quiz 5",
//     start: new Date(2025, 5, 17, 10, 0),
//     end: new Date(2025, 5, 17, 11, 0),
//     type: "quiz",
//     patientId: "P005sd",
//     patientName: "Charlie Lee",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-521-7890",
//     patient_email: "charlie.lee@example.com",
//     doctorId: "D001dsd",
//     doctorName: "Dr. Emily Carter",
//     reason: "Post-Surgery Consultation",
//     Note: "Patient is healing well.",
//     done: true,
//   },
//   {
//     title: "Quiz 5",
//     start: new Date(2025, 5, 17, 10, 0),
//     end: new Date(2025, 5, 17, 11, 0),
//     type: "quiz",
//     patientId: "P005sd",
//     patientName: "Charlie Lee",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-521-7890",
//     patient_email: "charlie.lee@example.com",
//     doctorId: "D001dsd",
//     doctorName: "Dr. Emily Carter",
//     reason: "Post-Surgery Consultation",
//     Note: "Patient is healing well.",
//     done: true,
//   },
//   {
//     title: "Survey 4",
//     start: new Date(2025, 5, 5, 4, 0),
//     end: new Date(2025, 5, 5, 5, 0),
//     type: "survey",
//     patientId: "P004",
//     patientName: "Dana White",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-246-8101",
//     patient_email: "dana.white@example.com",
//     doctorId: "D005",
//     doctorName: "Dr. Ethan Moore",
//     reason: "Routine Physical",
//     Note: "Patient reports no issues.",
//     done: false,
//   },
//   {
//     title: "Survey 5",
//     start: new Date(2025, 5, 6, 5, 0),
//     end: new Date(2025, 5, 6, 6, 0),
//     type: "survey",
//     patientId: "P005",
//     patientName: "Evan Parker",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-155-2468",
//     patient_email: "evan.parker@example.com",
//     doctorId: "D002",
//     doctorName: "Dr. Olivia Chen",
//     reason: "Medication Review",
//     Note: "Change in dosage recommended.",
//     done: true,
//   },
//   {
//     title: "Survey 6",
//     start: new Date(2025, 5, 7, 6, 0),
//     end: new Date(2025, 5, 7, 7, 0),
//     type: "survey",
//     patientId: "P006",
//     patientName: "Fiona Green",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-654-5210",
//     patient_email: "fiona.green@example.com",
//     doctorId: "D004",
//     doctorName: "Dr. Noah Reed",
//     reason: "Flu Symptoms",
//     Note: "Prescribed antiviral medication.",
//     done: true,
//   },
//   {
//     title: "Survey 7",
//     start: new Date(2025, 5, 8, 7, 0),
//     end: new Date(2025, 5, 8, 8, 0),
//     type: "survey",
//     patientId: "P007",
//     patientName: "George Young",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-777-8888",
//     patient_email: "george.young@example.com",
//     doctorId: "D001",
//     doctorName: "Dr. Emily Carter",
//     reason: "Skin Rash",
//     Note: "Referred to a dermatologist.",
//     done: false,
//   },
//   {
//     title: "Survey 8",
//     start: new Date(2025, 5, 9, 8, 0),
//     end: new Date(2025, 5, 9, 9, 0),
//     type: "survey",
//     patientId: "P008",
//     patientName: "Hannah Kim",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-666-1254",
//     patient_email: "hannah.kim@example.com",
//     doctorId: "D005",
//     doctorName: "Dr. Ethan Moore",
//     reason: "Allergy Test",
//     Note: "Mild pollen allergy diagnosed.",
//     done: true,
//   },
//   {
//     title: "Survey 9",
//     start: new Date(2025, 5, 10, 9, 0),
//     end: new Date(2025, 5, 10, 10, 0),
//     type: "survey",
//     patientId: "P009",
//     patientName: "Isaac Turner",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-909-8080",
//     patient_email: "isaac.turner@example.com",
//     doctorId: "D004",
//     doctorName: "Dr. Noah Reed",
//     reason: "Knee Pain",
//     Note: "Scheduled for MRI.",
//     done: false,
//   },
//   {
//     title: "Survey 10",
//     start: new Date(2025, 5, 11, 10, 0),
//     end: new Date(2025, 5, 11, 11, 0),
//     type: "survey",
//     patientId: "P010",
//     patientName: "Julia Adams",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-444-5522",
//     patient_email: "julia.adams@example.com",
//     doctorId: "D002",
//     doctorName: "Dr. Olivia Chen",
//     reason: "Diet Consultation",
//     Note: "Suggested Mediterranean diet.",
//     done: true,
//   },
//   {
//     title: "Survey 11",
//     start: new Date(2025, 5, 12, 11, 0),
//     end: new Date(2025, 5, 12, 12, 0),
//     type: "survey",
//     patientId: "P011",
//     patientName: "Kevin Brooks",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-555-2211",
//     patient_email: "kevin.brooks@example.com",
//     doctorId: "D005",
//     doctorName: "Dr. Ethan Moore",
//     reason: "Back Pain",
//     Note: "Prescribed physiotherapy.",
//     done: false,
//   },
//   {
//     title: "Survey 12",
//     start: new Date(2025, 5, 15, 12, 0),
//     end: new Date(2025, 5, 15, 15, 0),
//     type: "survey",
//     patientId: "P012",
//     patientName: "Laura Bell",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-888-9999",
//     patient_email: "laura.bell@example.com",
//     doctorId: "D001",
//     doctorName: "Dr. Emily Carter",
//     reason: "Pre-Surgery Consultation",
//     Note: "Discussed operation details.",
//     done: true,
//   },
//   {
//     title: "Survey 15",
//     start: new Date(2025, 5, 14, 15, 0),
//     end: new Date(2025, 5, 14, 14, 0),
//     type: "survey",
//     patientId: "P015",
//     patientName: "Mark Sloan",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-111-2222",
//     patient_email: "mark.sloan@example.com",
//     doctorId: "D002",
//     doctorName: "Dr. Olivia Chen",
//     reason: "Blood Pressure Monitoring",
//     Note: "BP levels stabilized.",
//     done: true,
//   },
//   {
//     title: "Survey 14",
//     start: new Date(2025, 5, 15, 14, 0),
//     end: new Date(2025, 5, 15, 15, 0),
//     type: "survey",
//     patientId: "P014",
//     patientName: "Natalie Ross",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-254-5678",
//     patient_email: "natalie.ross@example.com",
//     doctorId: "D004",
//     doctorName: "Dr. Noah Reed",
//     reason: "Headache Evaluation",
//     Note: "Ordered CT scan.",
//     done: false,
//   },
//   {
//     title: "Survey 15",
//     start: new Date(2025, 5, 16, 15, 0),
//     end: new Date(2025, 5, 16, 16, 0),
//     type: "survey",
//     patientId: "P015",
//     patientName: "Oscar Knight",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-111-9999",
//     patient_email: "oscar.knight@example.com",
//     doctorId: "D005",
//     doctorName: "Dr. Ethan Moore",
//     reason: "Post-Vaccine Follow-up",
//     Note: "No side effects reported.",
//     done: true,
//   },
//   {
//     title: "Survey 16",
//     start: new Date(2025, 5, 17, 16, 0),
//     end: new Date(2025, 5, 17, 17, 0),
//     type: "survey",
//     patientId: "P016",
//     patientName: "Paula Reed",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-222-5555",
//     patient_email: "paula.reed@example.com",
//     doctorId: "D002",
//     doctorName: "Dr. Olivia Chen",
//     reason: "Thyroid Checkup",
//     Note: "TSH level slightly elevated.",
//     done: false,
//   },
//   {
//     title: "Survey 17",
//     start: new Date(2025, 5, 18, 17, 0),
//     end: new Date(2025, 5, 18, 18, 0),
//     type: "survey",
//     patientId: "P017",
//     patientName: "Quincy Davis",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-444-0000",
//     patient_email: "quincy.davis@example.com",
//     doctorId: "D001",
//     doctorName: "Dr. Emily Carter",
//     reason: "Chest Pain Evaluation",
//     Note: "EKG results normal.",
//     done: true,
//   },
//   {
//     title: "Survey 18",
//     start: new Date(2025, 5, 19, 18, 0),
//     end: new Date(2025, 5, 19, 19, 0),
//     type: "survey",
//     patientId: "P018",
//     patientName: "Rachel Morgan",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-666-2222",
//     patient_email: "rachel.morgan@example.com",
//     doctorId: "D005",
//     doctorName: "Dr. Ethan Moore",
//     reason: "Diabetes Check",
//     Note: "Blood sugar under control.",
//     done: true,
//   },
//   {
//     title: "Survey 19",
//     start: new Date(2025, 5, 20, 19, 0),
//     end: new Date(2025, 5, 20, 20, 0),
//     type: "survey",
//     patientId: "P019",
//     patientName: "Samuel King",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-999-5555",
//     patient_email: "samuel.king@example.com",
//     doctorId: "D004",
//     doctorName: "Dr. Noah Reed",
//     reason: "High Cholesterol",
//     Note: "Advised lifestyle changes.",
//     done: false,
//   },
//   {
//     title: "Survey 20",
//     start: new Date(2025, 5, 21, 20, 0),
//     end: new Date(2025, 5, 21, 21, 0),
//     type: "survey",
//     patientId: "P020",
//     patientName: "Tina Brooks",
//     patientProfile: Prf1,
//     patient_phoneNumber: "555-000-1111",
//     patient_email: "tina.brooks@example.com",
//     doctorId: "D001",
//     doctorName: "Dr. Emily Carter",
//     reason: "Weight Loss Consultation",
//     Note: "Enrolled in wellness program.",
//     done: true,
//   },
// ];
