import { Prf1 } from "../../constants/Pics/Pics";
import { CalendarEvent } from "./CalenderInterface";

const now = new Date();
const CURRENT_YEAR = now.getFullYear();
const CURRENT_MONTH = now.getMonth(); // This will automatically use the current month (November 2025)

const dateAt = (day: number, hour: number, minute: number = 0) =>
  new Date(CURRENT_YEAR, CURRENT_MONTH, day, hour, minute);

export const myEventsList: CalendarEvent[] = [
  {
    title: "Survey 1",
    start: dateAt(2, 9),
    end: dateAt(2, 10),
    type: "survey",
    patientId: "P001",
    patientName: "Alice Johnson",
    patientProfile: Prf1,
    patient_phoneNumber: "555-125-4567",
    patient_email: "alice.johnson@example.com",
    doctorId: "D001",
    doctorName: "Dr. Emily Carter",
    reason: "Annual Checkup",
    Note: "Patient mentioned mild headaches.",
    done: true,
  },
  {
    title: "Survey 2",
    start: dateAt(4, 11),
    end: dateAt(4, 12),
    type: "survey",
    patientId: "P002",
    patientName: "Bob Smith",
    patientProfile: Prf1,
    patient_phoneNumber: "555-987-6545",
    patient_email: "bob.smith@example.com",
    doctorId: "D002",
    doctorName: "Dr. Olivia Chen",
    reason: "Follow-up Visit",
    Note: "Review of lab results.",
    done: false,
  },
  {
    title: "Survey 3",
    start: dateAt(6, 10),
    end: dateAt(6, 11),
    type: "survey",
    patientId: "P003",
    patientName: "Carla Mendes",
    patientProfile: Prf1,
    patient_phoneNumber: "555-333-7890",
    patient_email: "carla.mendes@example.com",
    doctorId: "D003",
    doctorName: "Dr. James Lee",
    reason: "Skin Rash",
    Note: "Prescribed ointment.",
    done: true,
  },
  {
    title: "Survey 4",
    start: dateAt(8, 9),
    end: dateAt(8, 10),
    type: "survey",
    patientId: "P004",
    patientName: "David Kim",
    patientProfile: Prf1,
    patient_phoneNumber: "555-444-8888",
    patient_email: "david.kim@example.com",
    doctorId: "D004",
    doctorName: "Dr. Noah Reed",
    reason: "Cold Symptoms",
    Note: "Advised rest and fluids.",
    done: false,
  },
  {
    title: "Survey 5",
    start: dateAt(10, 14),
    end: dateAt(10, 15),
    type: "survey",
    patientId: "P005",
    patientName: "Eva Long",
    patientProfile: Prf1,
    patient_phoneNumber: "555-666-1234",
    patient_email: "eva.long@example.com",
    doctorId: "D001",
    doctorName: "Dr. Emily Carter",
    reason: "Post-Surgery Checkup",
    Note: "Healing well.",
    done: true,
  },
  {
    title: "Survey 6",
    start: dateAt(12, 8),
    end: dateAt(12, 9),
    type: "survey",
    patientId: "P006",
    patientName: "Frank Nash",
    patientProfile: Prf1,
    patient_phoneNumber: "555-222-5678",
    patient_email: "frank.nash@example.com",
    doctorId: "D002",
    doctorName: "Dr. Olivia Chen",
    reason: "Back Pain",
    Note: "Prescribed physiotherapy.",
    done: false,
  },
  {
    title: "Survey 7",
    start: dateAt(14, 10),
    end: dateAt(14, 11),
    type: "survey",
    patientId: "P007",
    patientName: "Grace Lee",
    patientProfile: Prf1,
    patient_phoneNumber: "555-789-9999",
    patient_email: "grace.lee@example.com",
    doctorId: "D003",
    doctorName: "Dr. James Lee",
    reason: "Allergy Testing",
    Note: "Mild seasonal allergy confirmed.",
    done: true,
  },
  {
    title: "Survey 8",
    start: dateAt(16, 13),
    end: dateAt(16, 14),
    type: "survey",
    patientId: "P008",
    patientName: "Harry Ford",
    patientProfile: Prf1,
    patient_phoneNumber: "555-888-0000",
    patient_email: "harry.ford@example.com",
    doctorId: "D004",
    doctorName: "Dr. Noah Reed",
    reason: "Annual Blood Test",
    Note: "Results pending.",
    done: false,
  },
  {
    title: "Survey 9",
    start: dateAt(18, 9),
    end: dateAt(18, 10),
    type: "survey",
    patientId: "P009",
    patientName: "Isla Ray",
    patientProfile: Prf1,
    patient_phoneNumber: "555-111-2222",
    patient_email: "isla.ray@example.com",
    doctorId: "D001",
    doctorName: "Dr. Emily Carter",
    reason: "Thyroid Follow-up",
    Note: "No changes in condition.",
    done: true,
  },
  {
    title: "Survey 10",
    start: dateAt(20, 11),
    end: dateAt(20, 12),
    type: "survey",
    patientId: "P010",
    patientName: "Jake Olson",
    patientProfile: Prf1,
    patient_phoneNumber: "555-000-5555",
    patient_email: "jake.olson@example.com",
    doctorId: "D002",
    doctorName: "Dr. Olivia Chen",
    reason: "Nutrition Advice",
    Note: "Suggested Mediterranean diet.",
    done: true,
  },
  {
    title: "Survey 11",
    start: dateAt(22, 8),
    end: dateAt(22, 9),
    type: "survey",
    patientId: "P011",
    patientName: "Kate Hudson",
    patientProfile: Prf1,
    patient_phoneNumber: "555-321-4321",
    patient_email: "kate.hudson@example.com",
    doctorId: "D003",
    doctorName: "Dr. James Lee",
    reason: "Blood Pressure Check",
    Note: "Stabilized levels.",
    done: false,
  },
  {
    title: "Survey 12",
    start: dateAt(24, 12),
    end: dateAt(24, 13),
    type: "survey",
    patientId: "P012",
    patientName: "Liam Scott",
    patientProfile: Prf1,
    patient_phoneNumber: "555-654-7654",
    patient_email: "liam.scott@example.com",
    doctorId: "D004",
    doctorName: "Dr. Noah Reed",
    reason: "Headache Evaluation",
    Note: "CT scan recommended.",
    done: false,
  },
  {
    title: "Survey 13",
    start: dateAt(26, 15),
    end: dateAt(26, 16),
    type: "survey",
    patientId: "P013",
    patientName: "Mona Patel",
    patientProfile: Prf1,
    patient_phoneNumber: "555-999-1212",
    patient_email: "mona.patel@example.com",
    doctorId: "D001",
    doctorName: "Dr. Emily Carter",
    reason: "Routine Physical",
    Note: "No complaints reported.",
    done: true,
  },
  {
    title: "Survey 14",
    start: dateAt(28, 9),
    end: dateAt(28, 10),
    type: "survey",
    patientId: "P014",
    patientName: "Nathan Cole",
    patientProfile: Prf1,
    patient_phoneNumber: "555-000-7878",
    patient_email: "nathan.cole@example.com",
    doctorId: "D002",
    doctorName: "Dr. Olivia Chen",
    reason: "Post-Vaccine Follow-up",
    Note: "Minor arm soreness noted.",
    done: true,
  },
];
